### ISSUE TITLE
"cannot find module requests"

### ISSUE THREAD

**Issue by flatsiedatsie** [bewee/frontier-silicon-adapter#4]
After installing I got that error message popping up from the bottom of the window.

**Comment by bewee** [comment]
Have you installed the plugin from the add-on list or manually via git?

**Comment by bewee** [comment]
Do you still experience this problem?

**Comment by flatsiedatsie** [comment]
I installed it normally, but haven't used it since.

**Comment by bewee** [comment]
I guess by that you mean through add-on list.
Indeed, this module was not linked in the installation file on the mozilla server. Updated it there, should now be fixed. Closing this issue.
